const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
const keys=new Set();let muted=false,contrast=false,started=false,won=false,last=0,particles=[];
const world={width:6200,ground:602,stars:[],platforms:[],checkpoints:[{x:80,y:520,name:'forest edge'},{x:1700,y:520,name:'mushroom grove'},{x:3300,y:520,name:'stream bridge'},{x:4700,y:520,name:'ancestral clearing'}]};
for(let i=0;i<20;i++)world.stars.push({x:280+i*285+(i%3)*55,y:390-(i%4)*38,r:11,secret:false,got:false});
[[930,480,220],[1390,410,200],[1990,470,240],[2460,375,190],[2920,455,260],[3540,400,220],[4020,480,240],[4460,370,180],[5000,455,250],[5450,390,210]].forEach(([x,y,w])=>world.platforms.push({x,y,w,h:22}));
[[1200,300],[2670,260],[5180,270]].forEach(([x,y])=>world.stars.push({x,y,r:12,secret:true,got:false}));
const player={x:90,y:520,w:40,h:64,vx:0,vy:0,onGround:false,coyote:0,buffer:0,checkpoint:0};let camera=0;
function say(t,time=2.5){const el=document.querySelector('#message');el.textContent=t;el.classList.add('show');clearTimeout(say.timer);say.timer=setTimeout(()=>el.classList.remove('show'),time*1000)}
function reset(){const cp=world.checkpoints[player.checkpoint];player.x=cp.x;player.y=cp.y;player.vx=player.vy=0;say('A soft landing. Keep going.',1.4)}
function collected(){return world.stars.filter(s=>s.got).length}function stage(){return Math.min(4,Math.floor(collected()/5))}
function input(e,down=true){const k=e.key.toLowerCase();if(down){keys.add(k);if(k===' '||k==='w'||k==='arrowup')player.buffer=.13;if(k==='r')reset()}else keys.delete(k);if(down)started=true}
addEventListener('keydown',e=>{if([' ','arrowleft','arrowright','arrowup'].includes(e.key.toLowerCase()))e.preventDefault();input(e,true)});addEventListener('keyup',e=>input(e,false));
document.querySelectorAll('.touch-controls button').forEach(b=>{const k=b.dataset.key==='left'?'arrowleft':b.dataset.key==='right'?'arrowright':' ';b.addEventListener('pointerdown',()=>{keys.add(k);started=true;if(k===' ')player.buffer=.13});b.addEventListener('pointerup',()=>keys.delete(k));b.addEventListener('pointercancel',()=>keys.delete(k))});
document.querySelector('#soundButton').onclick=()=>{muted=!muted;document.querySelector('#soundButton').setAttribute('aria-pressed',muted);say(muted?'Sound off':'Sound on',1)};
document.querySelector('#contrastButton').onclick=()=>{contrast=!contrast;document.body.classList.toggle('high-contrast',contrast);document.querySelector('#contrastButton').setAttribute('aria-pressed',contrast)};
function spawn(x,y,n=8){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*80,vy:-Math.random()*80-20,t:.8})}
function update(dt){if(won)return;player.buffer=Math.max(0,player.buffer-dt);player.coyote=Math.max(0,player.coyote-dt);const left=keys.has('a')||keys.has('arrowleft'),right=keys.has('d')||keys.has('arrowright');const target=(right-left)*300;player.vx+=(target-player.vx)*Math.min(1,dt*9);if(!target)player.vx*=Math.pow(.001,dt);if((keys.has(' ')||keys.has('w')||keys.has('arrowup'))&&player.onGround)player.buffer=.13;if(player.buffer>0&&(player.onGround||player.coyote>0)){player.vy=-650;player.onGround=false;player.coyote=0;player.buffer=0}player.vy+=1700*dt;const oldY=player.y;player.x=Math.max(0,Math.min(world.width-player.w,player.x+player.vx*dt));player.y+=player.vy*dt;player.onGround=false;if(player.y+player.h>=world.ground){player.y=world.ground-player.h;player.vy=0;player.onGround=true;player.coyote=.1}for(const p of world.platforms)if(player.x+player.w>p.x&&player.x<p.x+p.w&&oldY+player.h<=p.y&&player.y+player.h>=p.y&&player.vy>=0){player.y=p.y-player.h;player.vy=0;player.onGround=true;player.coyote=.1}for(const s of world.stars)if(!s.got&&Math.hypot(player.x+20-s.x,player.y+30-s.y)<42){s.got=true;spawn(s.x,s.y);say(s.secret?'Secret star found!':'A star remembers you.',1.2)}for(let i=0;i<world.checkpoints.length;i++)if(player.x>world.checkpoints[i].x)player.checkpoint=i;document.querySelector('#checkpointText').textContent='Checkpoint: '+world.checkpoints[player.checkpoint].name;if(player.y>H+200)reset();if(player.x>world.width-180&&collected()>=20){won=true;say('The forest remembers its light.',8)}camera+=(Math.max(0,Math.min(world.width-W,player.x-W*.35))-camera)*Math.min(1,dt*4);particles=particles.filter(p=>(p.t-=dt)>0);particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=100*dt})}
function draw(){const s=stage(),night=['#111c42','#142952','#18345a','#1c4161','#24536a'][s];ctx.fillStyle=night;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(-camera,0);drawSky(s);drawWorld(s);drawPlayer();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.t);ctx.fillStyle='#ffe79a';ctx.fillRect(p.x,p.y,4,4)});ctx.restore();ctx.globalAlpha=1;document.querySelector('#progressText').textContent=`${collected()} / 23 stars`}
function drawSky(s){ctx.fillStyle='#f6d27a';for(let i=0;i<50;i++){const x=(i*197)%world.width,y=70+(i*83)%250;ctx.globalAlpha=.35+(i%3)*.2;ctx.fillRect(x,y,3,3)}ctx.globalAlpha=1;for(let i=0;i<world.width/180;i++){const x=i*180;ctx.fillStyle=s>1?'#193b4a':'#172b4e';ctx.beginPath();ctx.moveTo(x,groundY(480));ctx.lineTo(x+90,190+(i%3)*35);ctx.lineTo(x+180,groundY(480));ctx.fill()}}
function groundY(y){return y}function drawWorld(s){ctx.fillStyle=['#1b2948','#20374b','#254b50','#2d5b50','#39705a'][s];ctx.fillRect(0,world.ground,world.width,H-world.ground);for(let x=0;x<world.width;x+=150){ctx.fillStyle=s>2?'#47765c':'#2b4d52';ctx.beginPath();ctx.arc(x+40,world.ground,70,Math.PI,0);ctx.fill()}ctx.fillStyle='#5777b0';ctx.fillRect(3100,world.ground-6,700,8);ctx.fillStyle='#986e55';ctx.fillRect(3250,world.ground-38,300,15);for(const p of world.platforms){ctx.fillStyle='#48624e';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#83a36c';ctx.fillRect(p.x,p.y,p.w,6)}for(let x=700;x<world.width;x+=510){ctx.fillStyle=s>1?'#6bbd91':'#476a62';ctx.beginPath();ctx.arc(x,world.ground-12,30,Math.PI,0);ctx.fill();ctx.fillStyle='#efaa93';ctx.beginPath();ctx.arc(x-16,world.ground-34,8,0,7);ctx.arc(x+16,world.ground-34,8,0,7);ctx.fill()}ctx.fillStyle='#31514c';ctx.fillRect(5480,world.ground-250,28,250);ctx.fillStyle='#50745b';for(let i=0;i<7;i++){ctx.beginPath();ctx.arc(5495+(i%2)*80,300+i*36,80,0,7);ctx.fill()}for(const st of world.stars)if(!st.got){ctx.save();ctx.translate(st.x,st.y);ctx.rotate(Math.PI/4);ctx.fillStyle=st.secret?'#b7e8ff':'#ffe68e';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=18;ctx.fillRect(-st.r/2,-st.r/2,st.r,st.r);ctx.restore()}}
function drawPlayer(){ctx.save();ctx.translate(player.x+20,player.y);ctx.fillStyle='#151a2b';ctx.beginPath();ctx.moveTo(-19,20);ctx.lineTo(-13,0);ctx.lineTo(-4,9);ctx.lineTo(5,8);ctx.lineTo(15,0);ctx.lineTo(20,23);ctx.lineTo(16,57);ctx.lineTo(-15,57);ctx.closePath();ctx.fill();ctx.fillStyle='#d6a9a0';ctx.beginPath();ctx.arc(-8,24,4,0,7);ctx.arc(9,24,4,0,7);ctx.fill();ctx.fillStyle='#ffd95f';ctx.beginPath();ctx.arc(-8,23,2,0,7);ctx.arc(9,23,2,0,7);ctx.fill();ctx.fillStyle='#416bb2';ctx.beginPath();ctx.moveTo(-18,34);ctx.lineTo(20,34);ctx.lineTo(11,50);ctx.lineTo(-9,48);ctx.closePath();ctx.fill();ctx.fillStyle='#ffe076';ctx.fillRect(7,47,7,7);ctx.restore()}
function loop(t){const dt=Math.min(.032,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);canvas.focus();
